[package]
name = "cve-2017-10271-poc"
version = "0.3.1"
authors = ["刘安 <liuan@sgcc.com.cn>"]
license = "GPL-3.0"

[dependencies]
itertools = "*"
lazy_static = "*"
reqwest = "*"
termcolor = "*"
version = "*"